# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f12b63692a934af96cb27dbbfd148c2d4fbcc41d57064065c21ba18789abf02a4a145ee9fd1783107aeaeb5de039715e88f137895e0d66859746d18c1dbf83ae

test:
  secret_key_base: dc839db6e86a5afbb9723949808685289160369325b525dbd25c24148bafa74b675dca3f7d6653f21dba13a4b627ee0b2fd2a577a87295e6ddd9b7a26fd68876

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
