# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b743d83abe381e34e95c140acd93d36356a2aa3d92e00bf59723858a4cdf03852e48bc2fb488643780b7c73f05cc9e5bf8cb72497a85e8f821563b8b708e6c4

test:
  secret_key_base: 39587660276db597b5d68ab2800efa9a49cdd6ed2b33f39a9c2ba44f575489343a01f76d0e2f2e2bbc233687fa4fb040ecb0be1aca8ad0c93a3b2c3a49ef6cfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
